source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Trigger_Example', :exclusive => true do
  pod 'Trigger', :path => '../'
end

target 'Trigger_Tests', :exclusive => true do
  pod 'Trigger', :path => '../'

  
end
